### ISSUE TITLE
IsIterableContainingInOrder mismatch description is wrong

### ISSUE THREAD

**Issue by longtimeago** [hamcrest/JavaHamcrest#134]
Here is the example:
```java
List<String> expected = Arrays.asList("str0", "str1", "str2");
List<String> actual = Arrays.asList("str0", "strX", "str2");

List<Matcher<String>> matchers = expected.stream().map(Matchers::is).collect(Collectors.toList());
MatcherAssert.assertThat(actual, Matchers.contains(matchers));
```
Obviously, item 1 is different in both lists ("str1" != "strX" ).
But the AssertionError said:
```
Exception in thread "main" java.lang.AssertionError: 
Expected: iterable containing [<[is "str0", is "str1", is "str2"]>]
     but: item 0: was "str0"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
...
```

**Comment by sf105** [comment]
`is()` is just a sugar matcher that wraps the description, so you might not be getting what you expected. Can you try the same thing with `equalTo()` ?

**Comment by longtimeago** [comment]
@sf105 Thanks for the fast response!
It's exactly the same with `equalTo()` instead of `is()`

**Comment by sf105** [comment]
I think the problem is with overloading (damn Java generics). It's possible that `contains()` is interpreting the list of matchers as a list of items to be wrapped in `equalTo()`. It doesn't compile in Java 7. Can you post a test case?

**Comment by longtimeago** [comment]
@sf105 Isn't test case in the issue description enough?

**Comment by sf105** [comment]
No, because I can't get it to compile in my environment. I believe I'm the one doing this for free...

**Comment by longtimeago** [comment]
@sf105 OK, will try to do it tonight :)
