### ISSUE TITLE
`assertThat(0.0, equalTo(-0.0))` claims they are not equal

### ISSUE THREAD

**Issue by itamarst** [hamcrest/JavaHamcrest#167]
Consider the following program:

```java
import static org.junit.Assert.assertThat;
import static org.hamcrest.CoreMatchers.not;
import static org.hamcrest.CoreMatchers.equalTo;

class test {
    public static void main(String[]argv) {
        assertThat(0.0, equalTo(-0.0));
    }
}
```

When I run it I get:

```
Exception in thread "main" java.lang.AssertionError: 
Expected: <-0.0>
     but: was <0.0>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at test.main(test.java:7)
```

Junit 4.12, hamcrest 1.3.

**Comment by itamarst** [comment]
Oh, apparently it's just Java being awful: http://docs.oracle.com/javase/8/docs/api/java/lang/Double.html#equals-java.lang.Object-
