### ISSUE TITLE
Casted Type should not matter for containsInAnyOrder

### ISSUE THREAD

**Issue by thigg** [hamcrest/JavaHamcrest#301]
Regard following Example:

    @Test
    public void hamcrestTest(){
        String[] truth = new String[] {"1","2"};
        assertThat(Arrays.asList("1","2"),Matchers.containsInAnyOrder(truth));
        Object otherTruth = truth;
        assertThat(Arrays.asList("1","2"),Matchers.containsInAnyOrder(otherTruth));
    }

Result:
```
java.lang.AssertionError: 
Expected: iterable over [["1", "2"]] in any order
     but: Not matched: "1"

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at or.example.Example.hamcrestTest(Example.java:22)
```

The first assert is successfull the second isn't. 
This leads to very subtle bugs.

Version: hamcrest-core:1.3

Actual Behavior:
If an array is casted to an object, containsInAnyOrder (and most probably others) regards it as a single item. Thus it asserts that the array ["1","2"] is in the results.

Expected Behavior:
Both calls should behave the same.

**Comment by nhojpatrick** [comment]
@thigg please retest with org.hamcrest:hamcrest:2.2 as we have no plans to do any 1.x releases.

**Comment by thigg** [comment]
Still valid in 2.2. Confirmed correct version via:

```
     <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.hamcrest</groupId>
                    <artifactId>hamcrest-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
            <version>2.2</version>
            <scope>test</scope>
        </dependency>
```
(confirmed with dependency:tree)

and `  new AnyOf<>(null, null);` which is a 2.2 feature according to https://github.com/hamcrest/JavaHamcrest/pull/245

**Comment by gokareless** [comment]
@nhojpatrick could you please review #317

**Comment by gokareless** [comment]
@anyone?
