### ISSUE TITLE
containsInAnyOrder incorrectly identifies differences in identical collections

### ISSUE THREAD

**Issue by luskentyre-green** [hamcrest/JavaHamcrest#352]
When comparing two Lists or sets of characters, containsInOrder will report that a character is missing even when they sets or lists contain the same elements. The item reported as missing is always the character with the lowest ordinal value.

Code to reproduce: (hamcrest 2.2 plus JUnit 5)

```
package hamcrest.test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.containsInAnyOrder;
import static org.hamcrest.Matchers.is;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import org.junit.jupiter.api.Test;

class HamcrestTest {
  @Test
  void testTwoIdenticalSets() {
    Set<Character> testSetOne = new HashSet<>(Arrays.asList('!', '$', '-', '=', '+', '*'));
    Set<Character> testSetTwo = new HashSet<>(testSetOne);

    assertThat(testSetOne.containsAll(testSetTwo), is(true));
    // This assertion will fail, claiming that testSetOne does not contain '!'
    assertThat(testSetOne, containsInAnyOrder(testSetTwo));
   }

  @Test
  void testTwoMoreIdenticalSets() {
    Set<Character> testSetOne = new HashSet<>(Arrays.asList('$', '-', '=', '+', '*'));
    Set<Character> testSetTwo = new HashSet<>(testSetOne);

    assertThat(testSetOne.containsAll(testSetTwo), is(true));
    // This assertion will fail, claiming that testSetOne does not contain '$'
    assertThat(testSetOne, containsInAnyOrder(testSetTwo));
  }

}
```
output:

```
java.lang.AssertionError: 
Expected: iterable with items [<[!, $, *, +, -, =]>] in any order
     but: not matched: "!"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)

java.lang.AssertionError: 
Expected: iterable with items [<[$, -, =, +, *]>] in any order
     but: not matched: "$"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
```

**Comment by runeflobakk** [comment]
I suspect this is because there is no `containsInAnyOrder(..)` accepting a collection of the actual items to match, but there is an [overload accepting a collection with _matchers_](http://hamcrest.org/JavaHamcrest/javadoc/2.2/org/hamcrest/Matchers.html#containsInAnyOrder-java.util.Collection-) for every element which needs to match.

So e.g. in the example with the sets, you are in fact asserting that `testSetOne` must contain exactly _one_ element, and that single element should be `testSetTwo`. The code is invoking the [`T ...` vararg](http://hamcrest.org/JavaHamcrest/javadoc/2.2/org/hamcrest/Matchers.html#containsInAnyOrder-T...-) overload with one argument.
